build:
	xcodebuild -workspace TestMuckoSwift.xcworkspace/ -scheme TestMuckoSwift -destination 'platform=macOS,arch=x86_64' -showBuildTimingSummary -derivedDataPath ./DerivedData clean build
	./DerivedData/Build/Products/Debug/TestMuckoSwift
