source 'https://github.com/CocoaPods/Specs.git'

def pod_muckoswift
  pod 'MuckoSwift', '~> 0.1.6'
end

target 'TestMuckoSwift' do
  platform :osx, '10.13'
  pod_muckoswift()
end

target 'TestiOS' do
  platform :ios, '8.0'
  pod_muckoswift()
end
