source 'https://github.com/CocoaPods/Specs.git'

def pod_muckoswift
  pod 'MuckoSwift', git: 'https://github.com/wookay/MuckoSwift.git', branch: 'master'
end

target 'TestMuckoSwift' do
  platform :osx, '10.13'
  pod_muckoswift()
end

target 'TestiOS' do
  platform :ios, '11.4'
  pod_muckoswift()
end
